### ISSUE TITLE
Preview is not working

### ISSUE THREAD

**Issue by luciarodriguez** [Infragistics/livewire#129]
The previewer is not working; I pulled the latest last week just in case there were any changes. It is stuck at "Rendering..." and does not display anything, even after selecting a "version" and "product" in the lower dropdowns.

I'm using Mac Sierra (10.12.6) and the latest pull of Livewire.

**Comment by alhalama** [comment]
This appears to be because of changes in asciidoctor and if the version specified in bower.js is changed to "1.5.2" from "~1.5.2" it appears to resolve this.  I want to look closer at what has changed to see if there is a better fix to make though you should be able to use this as a workaround for now.
